// 排行榜
export const SET_RANKING_PARTITIONS = 'SET_RANKING_PARTITIONS'
export const SET_RANKING_VIDEOS = 'SET_RANKING_VIDEOS'
// loading 
export const SET_LOADING = 'SET_LOADING'
// 首页一级菜单
export const SET_ONE_LEVEL_PARTITIONS = 'SET_ONE_LEVEL_PARTITIONS'